import type { Product } from '@/lib/types';

export const products: Product[] = [
  {
    id: '1',
    sku: 'KR19-W42R-10',
    name: 'Royal Series 42" Wall Cabinet',
    description: 'Durable and spacious wall-mounted cabinet for commercial kitchens. Features stainless steel construction and sliding doors.',
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    specifications: [
      { key: 'Material', value: '18 Gauge Stainless Steel' },
      { key: 'Width', value: '42 inches' },
      { key: 'Depth', value: '12 inches' },
      { key: 'Height', value: '24 inches' },
      { key: 'Doors', value: '2, sliding' },
    ],
    documentation: [
      { name: 'Spec Sheet', url: '#' },
      { name: 'Installation Guide', url: '#' },
      { name: 'Warranty Information', url: '#' },
    ],
    relatedProducts: ['2', '3'],
  },
  {
    id: '2',
    sku: 'HS-1L',
    name: 'Hand Sink with Faucet',
    description: 'Compact hand sink with a gooseneck faucet, perfect for tight spaces. NSF listed.',
    images: ['https://placehold.co/600x400.png'],
    specifications: [
      { key: 'Material', value: '20 Gauge Stainless Steel' },
      { key: 'Bowl Size', value: '10" x 14" x 5"' },
      { key: 'Faucet', value: 'Included' },
    ],
    documentation: [{ name: 'Spec Sheet', url: '#' }],
    relatedProducts: ['1', '4'],
  },
  {
    id: '3',
    sku: '21-129L',
    name: 'Pre-Rinse Faucet Assembly',
    description: 'Heavy-duty pre-rinse assembly with a wall bracket for commercial dishwashing stations.',
    images: ['https://placehold.co/600x400.png'],
    specifications: [
      { key: 'Type', value: 'Wall Mount' },
      { key: 'Flow Rate', value: '1.15 GPM' },
      { key: 'Hose Length', value: '44 inches' },
    ],
    documentation: [{ name: 'Spec Sheet', url: '#' }],
    relatedProducts: ['1'],
  },
  {
    id: '4',
    sku: 'C-200',
    name: 'Underbar Ice Bin/Cocktail Unit',
    description: 'A 36" wide stainless steel ice bin and cocktail unit with a 10-circuit cold plate.',
    images: ['https://placehold.co/600x400.png'],
    specifications: [
      { key: 'Width', value: '36 inches' },
      { key: 'Capacity', value: '92 lbs of ice' },
      { key: 'Cold Plate', value: '10-circuit, sealed' },
    ],
    documentation: [{ name: 'Spec Sheet', url: '#' }],
    relatedProducts: ['2'],
  },
   {
    id: '5',
    sku: 'KR24-MS48L',
    name: '48" Mega-Top Sandwich Prep Table',
    description: 'Efficiently prepare sandwiches and salads with this 48" wide prep table, featuring a refrigerated base and a mega-top that holds 18 pans.',
    images: ['https://placehold.co/600x400.png'],
    specifications: [
      { key: 'Width', value: '48 inches' },
      { key: 'Pan Capacity', value: '18 (1/6 size)' },
      { key: 'Doors', value: '2' },
      { key: 'Refrigerant', value: 'R290' },
    ],
    documentation: [{ name: 'Spec Sheet', url: '#' }],
    relatedProducts: ['1', '2', '4'],
  },
];
